<?php
require_once ('config.php');

/* __autoload() function automatic includes the file wherever required
 * It first creates $class an array variable,then explode() the given input and stores in it
 * Now, $path variable is the path which is generated by "/" and the $class array using implode()
 */
function __autoload($class_name) {
	$class = explode("_" , $class_name);
	$path  = implode("/" ,$class ).".php";
	require_once($path);
}

?>